// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qkrxrpakjmmqusdvdpmw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFrcnhycGFram1tcXVzZHZkcG13Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY5MTA2NTQsImV4cCI6MjA3MjQ4NjY1NH0.0r2XSFz1HKv-obc7mOY9bSIwJltDfen92YbYtF9uMsY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});